flowchart LR
    %% Actors
    Professor(["Professor / Teaching Staff"])
    Student(["Student"])

    %% Use Cases
    subgraph Academic_Interactions [Student & Professor Interactions]
        UC_Edit([Edit Grades])
        UC_ViewForm([View Study Formations])
        UC_ViewGrades([View Grades])
        UC_ReqDoc([Request Documents])
        
        UC_Error([Display Validation Error])
    end

    %% Professor Interactions
    Professor --> UC_Edit
    Professor --> UC_ViewForm

    %% Student Interactions
    Student --> UC_ViewGrades
    Student --> UC_ReqDoc

    %% Extend Relationships
    UC_Error -.->|<<extend>>| UC_Edit